### ISSUE TITLE
Many physical constants are incorrect

### ISSUE THREAD

**Issue by AndrewBelt** [ggggggggg/Physical.jl#5]
In `/data/default/c_physics.jl`, many constants are blatantly wrong.

    const hbar_plank = 2*pi*h_plank # should be h_plank/(2pi)
    const m_electron = 9.10938291*KiloGram # forgot order of magnitude
    const m_proton = 1.672621777*Kilogram # forgot order of magnitude

There may be more. I may send a pull request later today.

**Comment by ggggggggg** [comment]
Fixed via ecbd7caaf57da64f0eaa91fcdd2a1d6d86172da3. Thanks and sorry for the obvious errors.
